name: sevnotes2
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_card: ^2.0.0
  cupertino_icons: ^1.0.2
  date_time_format: ^2.0.1
  ext_storage: ^1.0.3
  flutter_mobx: ^2.0.0
  get_it: ^7.1.3
  google_fonts: ^2.0.0
  mobx: ^2.0.1
  path_provider: ^2.0.2
  permission_handler: ^8.1.0
  shared_preferences: ^2.0.6
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  mobx_codegen: ^2.0.1+3
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
