name: sevnotes2
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  date_time_format: ^2.0.1
  ext_storage: ^1.0.3
  flutter_mobx: ^2.0.0
  get_it: ^7.1.3
  google_fonts: ^2.0.0
  mobx: ^2.0.1
  path_provider: ^2.0.2
  permission_handler: ^8.1.0
  shared_preferences: ^2.0.6
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  mobx_codegen: ^2.0.1+3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
