name: sevnotes2
description: A new Flutter project.

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  external_path: ^1.0.1
  animated_card: ^2.0.0
  date_time_format: ^2.0.1
  flutter_mobx: ^2.0.6+1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  mobx: ^2.0.7+4
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-4x.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo-4x.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
